### ISSUE TITLE
Support P2S addresses 

### ISSUE THREAD

**Issue by MrStahlfelge** [MrStahlfelge/ergo-wallet-android#7]
https://discord.com/channels/668903786361651200/669989266478202917/856509660122447952

Let's start with the simplest P2S (ErgoScript "true" - anybody can spend the funds you send to that address)
(mainnet):

4MQyML64GnzMxZgm

(testnet):

Ms7smJwLGbUAjuWQ

If it will work, you should try also a longer addresses, here's some proxy smartcontract p2s example (testnet):

J3JuxbRZSTFQrWtXY997t5vCi3dgBqWQjvd8Y5deJxQfxNF9ieaVegSSF7KGh9neCwovYasneYcKkcNXey7xsZbkiRbYLyENpoB242v7T5DQKUPLBSPCQoAVW8PzjC7d5pwdRPt82XLhMyVr3mh6pSmHkaQDej7YB7eoT3CDwVBNztZdNL61ksaSwifZQywzG5nsHiLnkYF1aW4izEY7drZxoM2TB3eksaQoNjVq5yG5QkVeEBPAg7GqtusVWg2xMLzzAS824SBB5twybJUUsoYqLtapWSow2A2miYht5dVjZs88UmynNVwLs9rv4kDhte9VXGxmcELSAKPoNvevoCBzFasMKnjRCeFjjYVhq1HhPYnzGMGeVxKD41rcgjoddqoRwBqmkcodhT1ck6za1bBsn6nnEXREvM4Pzd6TxBVQkRhaBwgHv2c2NLD8guEp4FbXoWVgHVCSN417tM4M9Td5DEXito5jdBc9kEawUwDg2X9UJ3ypGyAgXENLmVtMDa6xnNLFW2toS1f8KzaUEon

The wallet should be able to handle this long p2s addresses al

**Comment by aslesarenko** [comment]
Hint, use https://github.com/ScorexFoundation/sigmastate-interpreter/blob/cd8b1c43f0072c4a287786d82b5736a3a1e97673/sigmastate/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala#L36 example to convert string to ErgoAddress. Then construct org.ergoplatform.appkit.Address.

**Comment by MrStahlfelge** [comment]
More information:

> "how to construct an ErgoContract for P2S"
You can use https://github.com/ergoplatform/ergo-appkit/blob/3b4e8ee32e137f81db9afd4b167c1b706f0406d2/lib-impl/src/main/java/org/ergoplatform/appkit/impl/OutBoxBuilderImpl.scala#L25 method. And pass an instance of this class as argument https://github.com/ergoplatform/ergo-appkit/blob/7a8e7c028cf159663f838aaf81d937296685382c/lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoTreeContract.java#L7
This is when you know ErgoTree.
You can also use https://github.com/ergoplatform/ergo-appkit/blob/7a8e7c028cf159663f838aaf81d937296685382c/lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoScriptContract.java#L10 if you don't know ErgoTree but have contract source code (ErgoScript). The ErgoTree is created in getErgoTree method.
You also need to study https://github.com/ScorexFoundation/sigmastate-interpreter/blob/48cc739a77ca884456ed56759ce7b09f816a140b/sigmastate/src/main/scala/org/ergoplatform/ErgoAddress.scala#L67 and related classes. They are fully documented and there is also test specification https://github.com/ScorexFoundation/sigmastate-interpreter/blob/cd8b1c43f0072c4a287786d82b5736a3a1e97673/sigmastate/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala#L29

**Comment by MrStahlfelge** [comment]
Information and example for P2SH address: https://ergoplatform.org/en/blog/2019_07_24_ergo_address/
